--SET SEARCH_PATH TO PROJECT;

--SHOW SEARCH_PATH;
create schema project

CREATE TABLE PASSENGER
(
	USER_ID DECIMAL(5,0), 
	FNAME VARCHAR(20) NOT NULL,
	MNAME VARCHAR(20),
	LNAME VARCHAR(20) NOT NULL,
	MOBILE_NO DECIMAL(10) NOT NULL UNIQUE,
	EMAIL_ID VARCHAR(30) NOT NULL UNIQUE,
	AGE SMALLINT CHECK(AGE >= 18 AND AGE <= 100) NOT NULL,
	ADDRESS VARCHAR(50),
	PRIMARY KEY(USER_ID),
	UNIQUE(FNAME,MNAME,LNAME)
);

CREATE TABLE DRIVER
(
	DRIVER_ID DECIMAL(4,0), 
	STATUS BOOLEAN,
	FNAME VARCHAR(20) NOT NULL,
	MNAME VARCHAR(20),
	LNAME VARCHAR(20) NOT NULL,
	MOBILE_NO DECIMAL(10) NOT NULL UNIQUE,
	EMAIL_ID VARCHAR(30) NOT NULL UNIQUE,
	AGE INT CHECK(AGE >= 18 AND AGE <= 100) NOT NULL,
	ADDRESS VARCHAR(50),
	LICE_NO VARCHAR(16) UNIQUE,
	RATING DECIMAL(3,2) CHECK(RATING >= 0 AND RATING <= 5),
	lic_exp_year INT,
	PRIMARY KEY(DRIVER_ID),
	UNIQUE(FNAME,MNAME,LNAME)
);

CREATE TABLE KNOWN_LANGUAGES
(
	LANG VARCHAR(15),
	DRIVER_ID DECIMAL(4,0) NOT NULL,
	PRIMARY KEY(LANG,DRIVER_ID),
	FOREIGN KEY(DRIVER_ID) REFERENCES DRIVER(DRIVER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OWNER1
(
	OWNER_ID VARCHAR(5) PRIMARY KEY,
	CONTACT_NO DECIMAL(10,0) NOT NULL UNIQUE
);

CREATE TABLE CAR_INFO
(
	COLOUR VARCHAR(10) NOT NULL,
	MODEL_NO VARCHAR(10) PRIMARY KEY,
	CAR_TYPE VARCHAR(15) NOT NULL,
	SEAT_CAP SMALLINT NOT NULL
);

CREATE TABLE FUEL_TYPE
(
	MODEL_NO VARCHAR(10),
	FUEL_TYPE VARCHAR(10),
	PRIMARY KEY(MODEL_NO,FUEL_TYPE),
	FOREIGN KEY(MODEL_NO) REFERENCES CAR_INFO(MODEL_NO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE TAXI
(
	REG_NO VARCHAR(10) PRIMARY KEY,
	MODEL_NO VARCHAR(10) NOT NULL,
	OWNER_ID VARCHAR(5) NOT NULL,
	STATUS BOOLEAN,
	FOREIGN KEY(OWNER_ID) REFERENCES OWNER1(OWNER_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(MODEL_NO) REFERENCES CAR_INFO(MODEL_NO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE INDIVIDUAL
(
	AADHAR_NO DECIMAL(12) PRIMARY KEY,
	I_NAME VARCHAR(25) NOT NULL,
	OWNER_ID VARCHAR(5),
	FOREIGN KEY(OWNER_ID) REFERENCES OWNER1(OWNER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE TAXI_SERVICE_COMPANY
(
	TSC_ID VARCHAR(5)  PRIMARY KEY,
	TSC_NAME VARCHAR(25) NOT NULL,
	OWNER_ID VARCHAR(5),
	FOREIGN KEY(OWNER_ID) REFERENCES OWNER1(OWNER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE OFFER
(
	OFFER_ID VARCHAR(6) PRIMARY KEY,
	OFFER_TYPE VARCHAR(10),
	EXPIRY_DATE DATE,
	UNIQUE(OFFER_TYPE,EXPIRY_DATE)
);

CREATE TABLE RIDE
(
	BOOKING_ID DECIMAL(8) PRIMARY KEY,
	START_TIME TIME,
	END_TIME TIME,
	PICKUP_LOC VARCHAR(50),
	DROP_LOC VARCHAR(50),
	DATE_R DATE,
	DISTANCE DECIMAL(4),
	USER_ID DECIMAL(5,0) NOT NULL, 
	DRIVER_ID DECIMAL(4,0) NOT NULL, 
	OFFER_ID VARCHAR(6),
	REG_NO VARCHAR(10) NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES PASSENGER(USER_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(DRIVER_ID) REFERENCES DRIVER(DRIVER_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(OFFER_ID) REFERENCES OFFER(OFFER_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(REG_NO) REFERENCES TAXI(REG_NO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE SHIFTS
(
	SHIFT_ID SMALLINT PRIMARY KEY,
	START_TIME TIME,
	END_TIME TIME,
	UNIQUE(START_TIME,END_TIME)
);

CREATE TABLE WORKS_IN
(
	SHIFT_ID SMALLINT,
	DRIVER_ID DECIMAL(4,0),
	PRIMARY KEY(SHIFT_ID,DRIVER_ID),
	FOREIGN KEY(SHIFT_ID) REFERENCES SHIFTS(SHIFT_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(DRIVER_ID) REFERENCES DRIVER(DRIVER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE FEEDBACK
(
	FEEDBACK_ID DECIMAL(5) PRIMARY KEY,
	RATING_CAR SMALLINT CHECK(RATING_CAR >= 0 AND RATING_CAR <= 5),
	RATING_DRIVE DECIMAL(3,2) CHECK(RATING_DRIVE >= 0 AND RATING_DRIVE <= 5),
	SUGGESTIONS VARCHAR(50),
	USER_ID DECIMAL(5,0) NOT NULL, 
	BOOKING_ID DECIMAL(8) unique,
	FOREIGN KEY(USER_ID) REFERENCES PASSENGER(USER_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(BOOKING_ID) REFERENCES RIDE(BOOKING_ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE PAYMENT_DETAIL
(
	PAYMENT_ID DECIMAL(10) PRIMARY KEY,
	DATE_P DATE,
	STATUS BOOLEAN,
	PAY_TYPE VARCHAR(20),
	TIMME_P TIME,
	BOOKING_ID DECIMAL(8) UNIQUE,
	FOREIGN KEY(BOOKING_ID) REFERENCES RIDE(BOOKING_ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE BILL_DETAIL
(
	BILL_NO DECIMAL(8) PRIMARY KEY,
	TOLL_FEE INT,
	TAXES INT,
	TOTAL INT,
	BASE_FEE INT,
	AC_CHARGES INT,
	DISCOUNT INT,
	BOOKING_ID DECIMAL(8) UNIQUE,
	FOREIGN KEY(BOOKING_ID) REFERENCES RIDE(BOOKING_ID) ON UPDATE CASCADE ON DELETE RESTRICT
);